<?php
/**
 * @file
 * Code for the TCS Import feature.
 */

include_once 'tcs_import.features.inc';

/**
 * Redirect the Feeds Import Batch to the site homepage.
 *
 * @param array $batch
 *   The Batch process
 */
function tcs_import_batch_alter(&$batch) {
  // If this batch came from adding a source Feed.
  if('node/add/feed-source' == $batch['source_url']) {
    // Redirect to the homepage.
    $batch['form_state']['redirect'] = '<front>';
  }
}

/**
 * Implements hook_preprocess_node().
 */
function tcs_import_preprocess_node(&$vars) {
  switch ($vars['type']) {
    case 'feed_source':
      // Rewrite the title of Feed Source node pages.
      $vars['title'] = 'Source Feed: ' . $vars['title'];
      break;

  }
}
